parameters:
    # Adds a fallback VARNISH_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(VARNISH_URL): ''

api_platform:
    collection:
        pagination:
            client_items_per_page: true # Disabled by default
            items_per_page_parameter_name: limit # Default value
            maximum_items_per_page: 25
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    title: Hello API Platform
    version: 1.0.0
    # Enable the Varnish integration // Disable
#    http_cache:
#        invalidation:
#            enabled: false
#            varnish_urls: ['%env(VARNISH_URL)%']
#        max_age: 0
#        shared_max_age: 3600
#        vary: ['Content-Type', 'Authorization']
#        public: true
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\BaseBundle\Entity\User
    from_email:
        address: example@example.com
        sender_name: example

fos_oauth_server:
    db_driver: orm       # Drivers available: orm, mongodb, or propel
    client_class:        App\BaseBundle\Entity\Client
    access_token_class:  App\BaseBundle\Entity\AccessToken
    refresh_token_class: App\BaseBundle\Entity\RefreshToken
    auth_code_class:     App\BaseBundle\Entity\AuthCode
    service:
        user_provider : fos_user.user_provider.username_email
        options:
            access_token_lifetime: 3600